### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by cryptiklemur** [LFGamers/php-discord-bot#1]
Below is the Todo List
- [x] An ACL!

**_Core Module**_
- [x] Help
- [x] Eval
- [x] Stats
- [x] Ignore
- [x] Restart
- [x] Module
- [x] Prefix
- [x] Invite

**_Moderation Module**_
- [ ] Welcome
- [ ] Color
- [ ] Strike
- [ ] Mentions
- [ ] Names / Info
- [ ] Prune
- [ ] Poll/Vote
- [ ] Kick
- [ ] Ban
- [ ] Softban
- [ ] Temp Ban
- [ ] Mute
- [ ] Blacklist
- [ ] Anti-Advertisement

**_Fun Module**_
- [x] Karma
- [ ] Trivia
- [ ] Over 9000

**_LFG Module**_
- [ ] Advertisement
- [ ] LFG App Integration
- [ ] Channel Order Control
- [ ] Private voice channels

**_Events Module**_
- [x] Join/Leave Log
- [ ] Mod Log

**Comment by aequasi** [comment]
@RogueBurger & @tstave217

**Comment by VaronBros** [comment]
cool
